### ISSUE TITLE
请问这里面有详细的代码吗

### ISSUE THREAD

**Issue by zsgwq** [kalyanksk/yolo-ggcnn#1]

**Comment by zsgwq** [comment]
求将这两个网络结合的代码

**Comment by kalyanksk** [comment]
Here, I have used two ROS nodes using  the _run_yolo.py_ for YOLODetector and _run_ggcnn.py_ for DetectionNode. You can take idea from these and combine them to single code , if you like to.

**Comment by zsgwq** [comment]
Maybe I can improve the code and publish a paper?

**Comment by zsgwq** [comment]
Can this also be run in rviz in ubuntu20.04?

**Comment by kalyanksk** [comment]
There are similar literature who have used this approach you can follow them and if you have idea to improve them you can publish paper. I haven't tried with Rviz but you should be able to run it.

**Comment by zsgwq** [comment]
THANKS!

**Comment by zsgwq** [comment]
What version of python does this code run on?
I tried to run GGcNN with python=3.10 and found an error showing a matrix dimension mismatch when validating the set, so I had to downgrade to python=3.6, but yolov8
python>=3.8 is required, so what is your environment like?

**Comment by kalyanksk** [comment]
This code is tested with Python 3.10.12

**Comment by zsgwq** [comment]
ok ，i will try later.

**Comment by zsgwq** [comment]
well，I didn't have the part of ggcnn successfully running in the version of python=3.10.12.The following is the error message：
 data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\深度学习\ggcnn-master\ggcnn-master\utils\data\grasp_data.py", line 72, in __getitem__
    bbs = self.get_gtbb(idx, rot, zoom_factor)
  File "G:\深度学习\ggcnn-master\ggcnn-master\utils\data\jacquard_data.py", line 42, in get_gtbb
    gtbbs.rotate(rot, (c, c))
  File "G:\深度学习\ggcnn-master\ggcnn-master\utils\dataset_processing\grasp.py", line 42, in <lambda>
    return lambda *args, **kwargs: list(map(lambda gr: getattr(gr, attr)(*args, **kwargs), self.grs))
  File "G:\深度学习\ggcnn-master\ggcnn-master\utils\dataset_processing\grasp.py", line 42, in <lambda>
    return lambda *args, **kwargs: list(map(lambda gr: getattr(gr, attr)(*args, **kwargs), self.grs))
  File "G:\深度学习\ggcnn-master\ggcnn-master\utils\dataset_processing\grasp.py", line 315, in rotate
    self.points = ((np.dot(R, (self.points - c).T)).T + c).astype(np.int64)
ValueError: operands could not be broadcast together with shapes (4,2) (2,1)

**Comment by zsgwq** [comment]
But I ran it successfully in python version 3.6.

**Comment by Diskard** [comment]
请问你跑通了吗，最后有做改进嘛
